
#spring:
#    rabbitmq:
#        host: 192.168.1.202
#        port: 5672
#        username: test
#        password: test
# Single file max size
#multipart.maxFileSize: 100Mb
# All files max size
#multipart.maxRequestSize: 1000Mb
#spring.http.multipart.local:
# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:  # 只注册服务端
    registerWithEureka: false
    fetchRegistry: false
spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
     source: @java.version@
     target: @java.version@
