server:
  port: 8010
# Configure this Discovery Server
eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8671/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: consumer-movie