server:
  port: 8011
# Configure this Discovery Server
eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://root:root@peer1:8671/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true
spring:
  application:
    name: consumer-movie